export const N = {
  bg: 'var(--nh-bg)',
  raised: 'var(--nh-shadow-raised)',
  raisedSm: 'var(--nh-shadow-raised-sm)',
  raisedLg: 'var(--nh-shadow-raised-lg)',
  inset: 'var(--nh-shadow-inset)',
  insetDeep: 'var(--nh-shadow-inset-deep)',
  teal: 'var(--nh-teal)',
  tealDark: 'var(--nh-teal-dark)',
  tealDeep: 'var(--nh-teal-deep)',
  tealGlow: 'var(--nh-teal-glow)',
  text: 'var(--nh-text)',
  textLight: 'var(--nh-text-light)',
  textMuted: 'var(--nh-text-muted)',
  textWhite: 'var(--nh-text-white)',
  textTealLight: 'var(--nh-text-teal-light)',
};

export const neu = {
  raised: { boxShadow: 'var(--nh-shadow-raised)' },
  raisedSm: { boxShadow: 'var(--nh-shadow-raised-sm)' },
  raisedLg: { boxShadow: 'var(--nh-shadow-raised-lg)' },
  inset: { boxShadow: 'var(--nh-shadow-inset)' },
  insetDeep: { boxShadow: 'var(--nh-shadow-inset-deep)' },
  card: {
    background: 'var(--nh-bg)',
    borderRadius: '20px',
    boxShadow: 'var(--nh-shadow-raised)',
  },
  cardDark: {
    background: 'var(--nh-teal-deep)',
    borderRadius: '20px',
    boxShadow: 'var(--nh-shadow-card-dark)',
  },
  button: {
    background: 'var(--nh-teal)',
    color: 'var(--nh-text-white)',
    border: 'none',
    borderRadius: '50px',
    cursor: 'pointer',
    fontWeight: '700',
    fontFamily: "'Nunito', sans-serif",
    boxShadow: 'var(--nh-shadow-button)',
    transition: 'all 0.2s ease',
  },
  buttonPressed: {
    boxShadow: 'var(--nh-shadow-button-pressed)',
    transform: 'scale(0.97)',
  },
  iconButton: {
    background: 'var(--nh-bg)',
    border: 'none',
    borderRadius: '50%',
    cursor: 'pointer',
    boxShadow: 'var(--nh-shadow-raised-sm)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'box-shadow 0.2s',
  },
  searchBar: {
    background: 'var(--nh-bg)',
    borderRadius: '50px',
    boxShadow: 'var(--nh-shadow-searchbar)',
    display: 'flex',
    alignItems: 'center',
  },
  badge: {
    background: 'var(--nh-bg)',
    boxShadow: 'var(--nh-shadow-inset)',
    borderRadius: '20px',
    display: 'inline-block',
    fontSize: '10px',
    fontWeight: '800',
    letterSpacing: '1.5px',
    color: 'var(--nh-teal)',
  },
  statChip: {
    background: 'var(--nh-bg)',
    borderRadius: '12px',
    boxShadow: 'var(--nh-shadow-inset)',
  },
};


